**SO I AM IMPLEMENTING THE BACKPROPAGATION CODE WITHOUT USING KERAS**

IMPORTING LIBRARIES

In [274]:
import numpy as np
import pandas as pd

MAKING DATASET

In [275]:
dataset = pd.DataFrame([[8,8,4],[7,9,5], [6,10,6], [5,12,7]], columns=['CGPA','PROFILE_SCORE','PACKAGE'])


In [276]:
dataset

,CGPA,PROFILE_SCORE,PACKAGE
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


INITIALIZING THE VALUE FOR WEIGHTS AND BIASES

In [277]:
def initialize_parameter(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [278]:
initialize_parameter([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

DOT PRODUCT

In [279]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

IMPLEMENTING FORWARD PROPAGATION

In [280]:
def l_layer_forward(x , parameter):

  a = x
  L = len(parameter) // 2

  for l in range(1, L+1):
    a_prev = a
    Wl = parameter['W' + str(l)]
    bl = parameter['b' + str(l)]

    print("A"+str(l-1)+": ", a_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)


    a = linear_forward(a_prev, Wl, bl)
    print("A"+str(l)+": ", a)
    print("**"*20)


    return a, a_prev

In [281]:
from backcall.backcall import Parameter
x = dataset[["CGPA", "PROFILE_SCORE"]].values[0].reshape(2,1)
y = dataset[["PACKAGE"]].values[0][0]


parameter = initialize_parameter([2,2,1])


y_hat, A1 = l_layer_forward(x, parameter)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************


In [282]:
y_hat = y_hat[0][0]

In [283]:
A1

array([[8],
       [8]])

In [284]:
update_parameters(parameter, y, y_hat, x)

In [285]:
parameter

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

UPDATING THE WEIGHTS AND BIASES VALUES

In [286]:
def update_parameters(parameters, y, y_hat, x):

  paramter['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat) * A1[0][0])
  paramter['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat) * A1[1][0])
  paramter['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))


  paramter['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat) * paramter['W2'][0][0] * x[0][0])
  paramter['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat) * paramter['W2'][0][0] * x[1][0])
  paramter['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat) * paramter['W2'][0][0])


  paramter['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat) * paramter['W2'][1][0] * x[0][0])
  paramter['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat) * paramter['W2'][1][0] * x[1][0])
  paramter['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat) * paramter['W2'][1][0])


EPOCHS IMPLEMENTATION

In [287]:
paramter = initialize_parameter([2,2,1])

epochs = 5

for i in range(epochs):


  loss = []

  for j in range(dataset.shape[0]):

    x = dataset[["CGPA", "PROFILE_SCORE"]].values[j].reshape(2,1)
    y = dataset[["PACKAGE"]].values[j][0]

    y_hat, A1 = l_layer_forward(x, paramter)

    y_hat = y_hat[0][0]

    update_parameters(paramter, y, y_hat, x)

    loss.append(np.square(y - y_hat)**2)

  print("Epoch ------------------------------------ ", i+1, "Loss ----------------------- ", np.array(loss).mean())










A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10531456 0.10531456]
 [0.10531456 0.10531456]]
b1:  [[0.00066432]
 [0.00066432]]
----------------------------------------
A1:  [[1.68569728]
 [1.68569728]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11388934 0.11633927]
 [0.11450447 0.11713016]]
b1:  [[0.00188929]
 [0.00197716]]
----------------------------------------
A1:  [[1.83027003]
 [1.87131441]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.12563982 0.13592341]
 [0.12858742 0.14060174]]
b1:  [[0.0038477 ]
 [0.00432432]]
----------------------------------------
A1:  [[2.17509584]
 [2.37116228]]
****************************************
Epoch ------------------------------------  1 Loss -----------------------  249.51976508747148
A0:  [[8]
 [8]]
W1:  [[0.13929845 0.16870412]
 [0.14775434 0.18660235]]

**SO ABOVE CODE IS MANUALLY WRITTEN CODE NOW I WILL USE THE KERAS FOR THIS CODE**

In [288]:
import numpy as np
import pandas as pd

In [289]:
dataset2 = pd.DataFrame([[8,8,4],[7,9,5], [6,10,6], [5,12,7]], columns=['CGPA','PROFILE_SCORE','PACKAGE'])

In [290]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [291]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [292]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [293]:
model.get_weights()

[array([[ 0.62698305,  0.9931661 ],
        [-0.8675176 ,  1.2100967 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.24259222],
        [1.2106632 ]], dtype=float32),
 array([0.], dtype=float32)]

In [294]:
new_weights = [np.array([[0.1 , 0.1], [0.1 , 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [295]:
model.set_weights(new_weights)

In [296]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [297]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [298]:
model.fit(dataset.iloc[:, 0: -1].values, dataset['PACKAGE'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 27.8902  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.5895 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2646 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9235 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.5543 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.1996 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.8390 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.4484 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.0688 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.6455 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2457 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8282 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3829 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.9185 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.5043 
Epoch 16/75
4/4 ━━